org: salinsuwu
service: api-s3

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::164273947020:role/LabRole

functions:
  listaObjetosBucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: listaObjetosBucket
          method: post

  listaBuckets:
    handler: lista_buckets.lambda_handler
    events:
      - http:
          path: listaBuckets
          method: get

  crearBucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: crearBucket
          method: post

  crearDirectorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: crearDirectorio
          method: post

  subirArchivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: subirArchivo
          method: post
